version: '3.6'
services:
  discord:
    image: docker.aqi
    container_name: aqi_app
    ports:
      - "9999:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8000"
    tty: true
    networks:
      - greed_net 

networks:
  greed_net:
    name: greed_net
    external: true
      


